# ----------------------------------------------------------------------------------------------------------------------------
# 欢迎使用 ClassSays
# 不管怎么样，请看一下作者发癫写的东西（我们亲爱的自动补全AI都无法理解）q(≧▽≦q)
#
# ----------------------------------------------------------------------------------------------------------------------------
#
#
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣶⣷⠒⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⣀⡀⠀⠀⠀⣀⣀⠀⠀⠀⠀⣠⣴⡾⠟⠋⠁⠀⣾⡇⣷⠀⠀⢀⣀⣀⣤⢤⣤⡤⠤⠤⠄⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠔⠈⠉⣉⠥⠖⠲⠍⠒⠉⠀⠀⠐⠉⠁⠒⠿⣿⡇⠀⠀⠀⠀⢹⣇⣿⣴⠞⠁⠀⠀⠘⠃⠤⢀⠀⠀⠀⠀⠀⠉⠛⢐⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡜⣁⣤⠶⠋⠀⠀⠀⢀⠔⠁⠀⠈⢷⠲⢄⠀⠀⠀⠀⠙⢢⣄⠀⠀⣼⡷⣿⡁⢀⡀⢀⠀⠀⠀⠀⠀⠁⠲⢔⠒⠀⠄⡀⠀⠑⢈⠠⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡟⢏⡞⠁⠀⠀⠀⠀⣠⠋⠀⠀⠀⠀⠀⠱⡄⡑⣄⠀⠀⠐⢄⠙⢧⣾⣿⣿⣽⡟⠁⠀⠀⠈⠙⠲⡀⠀⠀⢀⠠⡑⠄⠀⠀⠁⠠⡀⢡⢴⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣄⠀⠀⠀⠀⠀⠀⢀⡿⢑⡟⠀⠀⠀⠀⠀⢠⠃⡀⠀⠀⠀⠀⠀⠀⠸⣶⡀⠳⡀⠀⠀⠱⡈⢿⣿⣿⢾⣇⠀⠀⠀⠀⠀⠀⠘⣆⠈⠀⠂⢈⠀⠁⢄⠀⠀⠈⠢⡆⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣤⠴⠖⠒⠉⠺⣯⢳⣿⣦⣄⠀⠀⠀⣸⡤⢋⠔⠀⠀⠀⠀⢀⡇⢰⠀⠀⠀⠀⠀⠀⡀⠘⢇⠉⠢⡘⢆⠀⠀⡘⢼⡽⣿⠟⣋⢳⡀⠐⢦⠀⠀⠀⠘⣆⠀⢀⠀⠈⠂⢀⠑⢄⠀⠀⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⢠⠾⠃⠁⠀⠀⢀⠔⢉⣉⢙⣷⡿⣷⣿⠿⣒⣤⡯⡾⠁⠀⢠⠀⠀⢀⡼⠀⡾⣴⠈⡅⠀⠀⠀⡇⠠⢸⠉⠉⠘⢮⣦⠄⠹⡈⡟⢞⣷⣌⠒⡜⣦⠀⠳⡀⠀⠀⢹⡆⠀⠀⠄⠀⠀⠁⠀⡑⢔⡰⠈⢂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠛⠁⢀⡀⠤⠐⢒⣉⢉⡤⠀⠀⠈⢻⣿⣿⣶⢾⡿⣿⠇⡔⢠⠇⠀⢀⠏⡇⣰⣷⡟⠀⡇⢀⠀⠀⡇⠀⣿⠀⣀⣀⣀⢻⣶⠀⣇⢸⠀⢿⣷⡩⠔⡜⣧⡀⠹⡄⠀⠀⢻⢦⠀⢀⠈⠀⠀⠀⠀⠢⡑⢄⠀⢂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⢞⠡⠐⢈⡠⠄⠒⢉⠏⡠⠋⠀⣀⣠⡶⠞⠛⣿⣿⣿⣞⣽⡜⢠⡞⠀⠀⡼⣸⢲⡟⢸⡇⢰⢧⠈⡆⢰⠃⢠⣧⣿⣿⣿⣟⢻⣿⡆⣸⡬⡇⠘⣿⣯⢲⢈⠜⡷⡀⠸⡄⠀⠘⣧⢣⠀⠀⠐⠈⠀⠀⠀⢻⢦⡘⢆⢄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠔⠋⢁⠄⠂⠁⡠⠀⢁⡮⠊⢀⣴⡺⠛⠁⠀⢀⡤⠿⣿⣿⣿⡾⢀⣾⠇⠠⡼⣱⢻⡜⣠⣿⡷⣾⣾⢀⡧⡞⠀⣼⡏⠸⣏⣭⣱⣀⢻⢣⣿⡷⡇⠀⣿⠸⡌⢧⢈⢳⠘⢄⠘⡄⠀⢹⣆⢣⠀⠠⠀⢀⠀⠀⠘⣏⢻⡄⠣⡚⠵⢦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡔⠁⠄⠊⠀⢀⠔⠀⠀⣀⠎⠀⣰⠛⠁⠀⠀⢀⡴⠋⠀⠀⣿⣿⣿⡇⣼⣿⢀⣷⣡⣿⢸⣿⢿⣏⠼⠛⣦⢟⣿⡠⢺⡟⠀⠀⠀⠀⠀⠀⡞⣿⢻⣿⡃⢀⣿⠂⢹⡌⠇⠘⡆⠈⢢⠹⡀⠈⣯⢃⢣⠀⠀⠀⡀⠀⠀⡿⡌⢿⡆⠘⣆⠀⠀⠙⠒⠤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠌⢁⢴⠏⠀⠀⠐⠁⢀⠤⠞⠁⠴⠋⠀⠀⠀⠀⡰⠋⠀⠀⠠⠀⣿⣷⣿⣶⠉⣧⢸⣷⣿⣿⣞⠛⠴⠻⠐⠈⢀⡜⠁⠀⠀⠀⠀⠀⠀⠀⠀⠐⠵⣿⣜⡟⠠⣼⡿⠀⠈⣷⠘⠀⣧⠀⠀⠱⣷⠀⢻⡼⣯⡆⠀⠀⠀⠀⠀⢣⢹⢎⡜⢆⠀⡕⢄⠀⠀⠀⠈⠑⠢⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡐⠁⠔⠁⡟⢀⠀⠁⣠⡦⠁⠂⠀⠈⠀⠀⠀⠀⡠⠊⠀⢀⠀⠂⠀⢈⣽⢯⡟⢻⡀⢸⣿⣿⣿⣿⣿⣲⣤⡀⠀⠀⠁⠀⠀⠀⠀⡀⢤⣤⣤⡀⠀⠀⠀⣿⣿⣔⠡⠋⠀⠀⠀⢹⡀⠀⡇⠀⠀⠀⠸⡆⢸⣷⣏⣿⠀⠀⠀⠀⠀⣸⢸⠈⢻⡀⡆⠘⡄⠢⡀⠀⠀⠀⠀⠀⠘⢦⢄⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠌⢠⠊⠀⢸⡇⠀⢀⣞⠟⠀⠀⠀⠀⠀⠀⠀⣠⠞⠁⠀⠠⠀⠀⠄⢈⣾⢯⠞⠀⠈⠂⠀⠻⣿⣿⣿⣿⣷⣌⠙⢦⡀⠀⠀⠀⢰⠋⠉⠀⠀⣰⠁⠀⠀⡜⠙⠉⠀⠀⠀⠀⠀⠀⠸⠁⠠⡇⠀⠀⠀⠀⢻⠘⡟⣹⢸⡆⠀⡀⠂⠀⣧⢸⠀⠀⢷⢱⠀⢹⣀⠘⢤⡀⠀⠀⠀⠀⠀⠐⢈⠢⡀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡌⢠⠁⠀⡐⢹⠀⢠⣿⠏⠀⠀⠀⠀⠀⠀⢀⠔⠃⠀⠀⢀⠀⠄⠂⢀⡾⣣⠋⠀⠀⠀⠀⠀⠀⠈⠿⢿⣿⣿⣿⣷⣬⡇⠀⠀⠀⠀⠁⠒⠒⠂⠁⠀⡠⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⣆⠀⢸⠁⠀⠀⠀⠀⠘⣠⠁⣯⠘⣧⢀⡇⠀⢠⠃⣸⠀⠀⠈⣿⡀⠘⡝⢆⠀⠲⡀⠀⠀⠀⠀⠀⠀⠑⡈⢄⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⡘⢀⠃⢀⠊⠀⢸⢀⣿⠂⠀⡌⠐⠀⠀⠀⠠⠊⠀⠀⠀⠠⠀⠀⡀⣠⣟⠝⠅⠀⠀⠀⠀⠀⠀⠀⢀⠈⢂⠈⠉⠉⠉⠙⠚⢻⢿⡦⣀⡀⠀⠀⠀⢀⡔⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⢡⠁⡎⠀⠀⠀⠀⠀⢸⣹⠀⢹⠆⡟⡸⠀⢠⡏⠀⣇⠀⠀⢰⢸⠀⠀⡇⠈⢦⠀⠐⡐⠄⠀⠀⠀⠀⠀⠘⡀⢂⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⢠⠇⡌⠠⠁⠀⠀⠈⡟⠁⠀⣸⠀⠀⠀⠀⠀⠔⠀⠀⠀⠌⠀⢀⣴⣾⠷⣇⠌⠀⠀⠀⠀⠀⠀⡠⠊⠀⠀⠈⠉⡒⢤⣦⣤⠐⠚⠀⠉⠢⣀⠉⠁⠊⠁⢻⠢⠀⠀⠀⠀⢀⣀⢀⣀⡠⠃⠈⡸⠀⠀⠀⠀⠀⠀⢾⠃⠀⠘⢸⡟⠁⡠⠃⠀⢸⠁⠀⠀⠆⢸⠄⠀⡇⠀⠀⠣⡀⠘⡄⠢⡀⠀⠀⠀⠀⢰⠀⢇⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⢸⢲⡰⠁⠀⠀⠀⣰⠁⠀⢰⠃⠀⠀⠀⢀⠂⠀⠀⡀⠂⢀⡴⣫⣾⠋⢸⠁⠀⠀⠀⠀⠀⠀⢠⠁⠀⠀⠀⠀⠀⠈⠀⢻⡎⢧⠀⠀⠀⠀⠀⢑⢦⣄⢠⡞⠀⠑⡴⣖⠊⠁⠀⠀⠀⠈⠑⢶⠁⠀⠀⠀⡀⢀⢞⠎⠀⠀⣠⠟⣠⠎⠁⠀⠀⠇⠀⠀⡰⠀⡘⠀⠀⡏⠀⠀⠀⢱⡀⠈⡄⠐⠄⠀⠀⠀⠀⡇⠈⡄
# ⠀⠀⠀⠀⠀⠀⠀⠀⡜⡜⠀⠀⠀⢀⣼⡏⠀⠀⡀⠀⠀⠀⣠⠣⠂⠀⠀⣀⢔⣩⠞⢡⠇⠀⢼⠀⠀⠀⠀⠀⠀⠀⡏⠀⠀⠀⠀⠀⠀⠀⠀⠈⣏⠈⢆⠀⢀⡠⠊⣰⣟⡾⠚⠿⣆⠀⢱⡘⣆⠀⠀⠀⠀⠀⠀⠀⠈⣤⣀⣀⠔⠡⠏⢒⡲⢝⠥⠊⠀⠀⠀⠀⢸⠀⠀⡐⠀⣠⠁⠀⢰⠃⠀⠀⠀⠀⢷⡀⠘⡀⠈⢂⠀⠀⠀⢁⠀⡇
# ⠀⠀⠀⠀⠀⠀⠀⢠⡵⡇⠀⠀⠠⣻⢳⠁⠀⢀⠀⠀⠀⣰⢧⠃⠀⣠⢖⡵⢛⠡⠂⡟⠀⣴⣼⠀⠀⠀⠀⠀⠀⠀⡇⣀⠠⠤⠄⣀⠀⠀⠀⢀⡇⠀⡨⢶⠁⠀⣰⠋⢹⣅⠀⠀⢡⠑⡄⢷⠈⢧⡀⠀⠀⠀⠀⠀⠀⠙⠾⣖⡰⠒⠉⣁⣴⠋⠀⠀⠀⠀⠀⣠⢿⠀⠌⢀⡴⠁⠀⣠⠆⠀⠀⠀⠀⠀⢸⡷⠀⢰⠀⠀⠢⠀⠀⢨⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⣼⡇⡇⠀⡰⢡⠏⠀⠀⠀⠄⠀⠀⢲⣏⠎⣠⣾⠷⠛⠀⠁⠀⢸⠄⠀⡏⢻⡀⠀⠀⠀⠀⣠⣴⣿⣾⣷⣶⣶⣦⡕⢄⢀⣿⡕⠊⠀⠈⢧⣰⠃⠀⠀⢹⡖⠖⠚⡇⠈⢢⡆⠀⠡⡀⠀⠀⠀⠀⠀⠀⠀⢀⠜⣹⣾⣿⣦⣤⣤⣤⣠⣄⣴⢃⡗⠒⢊⠉⠀⢀⠔⠃⠀⠀⠀⠀⠀⠀⠀⣷⢣⠀⢃⠀⠀⢂⠀⡔⠀⡀
# ⠀⠀⠀⠀⠀⠀⠀⡟⡇⢠⠜⠀⡞⠀⠀⠀⠠⠀⠐⢠⡟⠞⣰⡛⠁⠀⠀⠀⠀⢀⣸⣤⣶⣷⣾⣷⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣏⣼⠁⠀⠀⠀⠘⠁⠀⠀⠀⠀⡇⠀⠀⠰⠀⠀⠁⠀⠠⠈⢏⠢⡀⠀⠀⠀⢀⠆⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣮⣁⡠⠔⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⡎⢆⠸⡄⠀⠀⡄⡇⠀⡇
# ⠀⠀⠀⠀⠀⠀⢠⡇⠅⡜⠀⢰⠃⠀⠀⠀⠠⠀⠀⣾⡵⠒⠙⠵⣄⠀⢀⡀⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢷⠀⠀⠀⣆⠀⠀⠀⠀⠀⠊⠶⣗⠢⣄⡀⣸⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠱⢸⠀⣧⠀⠀⢱⠃⣠⡇
# ⠀⠀⠀⠀⠀⠀⣸⣂⣎⡀⢀⡎⠀⠀⠀⢀⣄⣠⣼⣷⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢺⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⢄⠹⡖⢶⣸⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣄⡀⠀⠀⠀⠀⠀⡇⠀⡀⡇⢸⠑⡀⡌⡐⣿⠁
# ⠀⠀⠀⠂⠉⠉⢁⠏⠀⠈⢩⠈⠁⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠈⢻⣿⣿⣿⣿⣿⣿⣿⡿⠁⢡⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⡀⠀⠀⠀⢇⠀⠀⠀⠀⠀⠀⠀⠅⢘⡆⣌⠽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢶⣤⣀⠀⠀⡇⠀⢿⢱⣜⣦⡾⡋⣰⠏⠀
# ⠀⠀⠀⠀⠀⣠⠂⠀⠄⠠⠁⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠓⠠⠤⢄⣀⡀⠀⠀⠀⠀⢹⣿⣿⣿⣿⣿⡿⠁⠀⠀⠣⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠘⡄⠀⠀⠀⠀⠀⠀⡀⢸⢫⣜⢺⡝⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⢋⠉⠹⡀⠀⠀⠀⠈⠻⣶⡇⠀⠘⣟⡟⠉⢢⣸⡟⠀⠀
# ⠀⠀⠈⠉⠀⠀⠀⠀⢀⡀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠐⣇⡀⡠⠆⠀⢀⣤⣷⣾⣿⣿⣿⣿⡿⡇⠀⠀⠀⠀⠈⠒⠤⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠄⢀⡇⠀⠀⠀⠀⠀⠀⢁⣏⣷⣎⠿⠼⢓⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣤⣄⣂⢰⠀⠑⡀⠀⠀⠀⠀⠙⢇⠀⡄⢾⠁⠀⣠⠟⢡⠀⠀
# ⠀⠀⠀⠀⢀⡤⠔⠊⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠋⠀⠀⠀⠀⡀⠈⠪⡀⣠⣴⣿⣿⣿⣿⣿⣿⣿⠟⠀⢱⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠀⠂⠀⢸⠁⠀⠀⠀⢠⠇⠀⠀⠀⠀⠀⢠⠊⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠈⠢⡀⠀⠀⠀⠀⠑⠧⡉⡤⠐⠁⢸⠀⡆⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠁⠀⠀⠀⠀⢀⣴⠝⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⠋⠀⠀⠸⡄⠀⠀⠀⠀⠠⠀⠈⠀⠀⠀⠀⠀⡜⠀⠀⠀⠀⣸⠀⠀⠀⠀⠀⠀⡎⠀⠀⠀⢀⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠙⠳⠖⣂⣄⡀⠈⠐⠂⢤⠈⡄⢡⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣴⣾⠿⡟⠻⢿⣿⣿⣿⡿⠟⢋⠁⠀⣠⣖⠂⠀⠀⡛⠁⠀⠐⠶⣘⣿⣿⣿⣿⣿⣿⠟⠁⠀⠀⠀⠀⣇⣀⠤⠨⠄⠀⠀⠀⠀⠀⠀⠀⣰⠁⠀⠀⠀⠀⡇⠀⠀⠀⠀⢀⠀⣇⡀⢤⡶⠋⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡄⠀⠀⠀⠀⠀⠀⠀⢿⣏⣿⠀⠉⠁⠀⡇⢸⠀
# ⠀⠀⠀⠀⠀⠀⠀⣀⣴⣾⣻⠟⠋⠀⠀⣦⠀⠀⠈⠻⣿⣿⣶⣶⣿⣿⣿⣿⢀⠔⠊⠀⠀⠀⠀⠀⠈⠿⢿⣿⣿⠟⠁⠀⠀⠀⠀⠀⡜⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⠿⣿⡶⠀⠀⢸⠇⠀⠀⠀⢀⠂⡜⠛⠉⢠⠁⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃⢠⡄⠀⡀⠀⢰⡆⠈⢷⡏⠀⠀⠀⠀⡅⢸⠀
# ⠀⠀⠀⠀⢊⣵⣾⢿⡹⡏⠀⠀⠀⠀⠀⣻⠀⠀⠀⠀⠈⠻⣿⣿⣿⣿⣿⣿⡆⠀⡀⠀⠀⢀⠀⠰⣥⣤⡦⠴⢌⣐⣄⠀⠀⢀⣠⠞⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠜⣿⣄⣀⠀⠀⠀⡼⠀⠀⠀⠀⢁⠌⠀⠀⠀⡇⠠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⢠⣾⣿⠀⢠⣿⠀⢸⡞⡄⠈⡇⠀⠀⠀⠀⠇⡈⠀
# ⠀⠀⣴⣵⣿⣿⠓⠊⠁⡀⠀⠀⠀⠄⠀⢻⡀⠀⠀⠀⠀⠀⠈⠛⠿⣿⣿⣿⠁⢨⣿⡄⠀⣿⣎⢆⠹⡉⠀⠀⠀⠀⣀⠤⠒⠁⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠂⢰⠋⠛⠋⠀⠀⠀⡇⠀⠀⠀⡠⠃⠀⠀⠀⢸⠀⠀⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡃⣰⣿⣿⡏⠀⣾⣿⡇⢸⣷⠝⡄⠘⡄⠀⠀⢰⠀⠃⠀
# ⠀⠐⢻⡏⠇⠘⣆⠀⠀⢀⠀⠀⠂⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⣹⠀⡜⠛⣷⠀⡇⠀⠱⡀⠐⡀⠀⣠⠊⠀⠀⠀⢰⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠔⠁⢀⡏⠀⠀⡀⠠⠐⢸⠀⠀⠀⡜⠀⠀⠀⠀⠀⡠⠔⠉⠀⢛⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⢸⣿⣿⡇⠀⣯⠀⠘⢄⠐⡄⢀⠆⡘⠀⠀
# ⠐⠀⢸⡤⠘⢄⠙⣆⠀⠐⡀⠀⠀⠀⠀⠀⢧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡏⠀⡇⠀⢹⡀⢧⣀⣀⣘⡆⠘⣴⡇⠀⠀⠀⠀⠸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⡼⠀⠀⡐⠀⠀⠀⡇⠀⠀⡔⠀⠀⠀⡠⠔⠉⠀⣀⠔⡎⠀⠐⡀⠙⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⣿⣿⣿⣿⡄⢸⢀⠇⠀⠉⢁⠎⡐⠀⠀⠀
# ⠀⠀⠀⣿⠀⠈⢢⠈⢦⠀⢧⠀⠀⠀⠀⠀⠸⣆⠀⠀⠀⠀⠀⠀⠀⠀⢀⡃⡰⠁⠀⢈⡇⢸⣿⣿⣿⣿⡄⣿⡇⠀⠀⠀⠀⠀⢳⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⠁⠀⡐⠀⢀⠈⡸⠀⠀⣰⣀⠠⠔⠉⠀⢀⠔⠉⠘⡀⠘⡀⠀⠈⢤⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⠟⠁⠐⠼⡎⠀⠀⢠⠊⠌⠀⠀⠀⠀
# ⠀⠀⠀⠹⡇⠀⠀⠑⢌⠄⠘⣦⠀⠀⠀⠀⠀⢿⠢⡀⠀⠀⠀⠀⠀⠀⠘⠗⠁⢀⡞⣿⡇⢰⣿⣿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠑⡀⠀⠈⠀⠀⠀⠀⠀⣰⠃⠀⠄⠀⠄⠂⢠⠃⠀⢼⠏⠀⢀⡀⠤⠒⠀⠀⠀⠀⠈⢀⠐⠄⠀⠎⠈⡟⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⡟⠁⠀⠀⠀⡰⠀⢀⠔⡡⠊⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠘⣄⠀⠀⠀⠑⢄⠹⣇⠀⠀⠀⠀⠈⢆⠈⠢⣀⠀⠀⠀⠀⠀⠀⠀⢸⠁⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠈⠂⡀⠀⠀⠀⢀⡰⠃⠀⡀⠂⠈⢀⢀⠞⢈⠔⠁⠘⡬⠳⠒⠶⠖⠶⠶⣖⣒⡲⠲⠶⢦⣿⣄⡰⠁⠀⠀⠀⠉⠉⠛⠛⠛⠻⠛⠛⠛⢋⠝⠁⠀⡔⠁⠀⢠⡖⡰⢁⠔⡡⠊⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠘⢄⠀⠀⠀⠸⠉⢻⣧⡀⠀⠀⠀⠘⡖⠤⣀⠉⠒⠠⠤⢀⣀⡀⢸⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⡐⠀⠐⠠⣠⣼⣿⠁⠠⠐⠀⠠⠁⢀⣾⠒⠁⡀⠀⠀⣣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠙⠲⠮⠩⣙⣲⣄⡀⠤⠠⠤⣀⣀⡀⢁⡴⠚⠁⠀⢀⠎⠀⣀⣴⠟⣀⠭⠐⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⢃⠀⢷⡐⠄⠀⠀⠀⠘⠄⠀⠈⠉⠑⠂⠒⠀⠀⣏⢹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀⠀⠀⠔⠀⢠⣴⣿⣿⣿⣿⠀⠄⠀⡁⠐⣠⡞⠈⠀⢰⠁⠀⢠⣿⡈⠳⣀⠈⢋⠉⠉⠉⠉⠉⠉⠉⠉⠉⠀⠒⠤⡀⠈⠒⠄⡀⢀⡠⠜⠁⠀⠀⢀⡰⠥⠤⠊⡠⡣⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠄⠈⢧⡈⠢⡀⠀⠀⠈⢦⡀⠀⠀⠀⠀⠀⠀⢸⡄⢿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⢊⣠⣾⣿⣿⣿⣿⣿⣿⠀⠐⣀⣴⣾⣿⣷⠀⡇⠀⠀⢀⣿⣿⣷⡀⠈⠑⠄⡡⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢢⡬⠕⠊⠁⠀⠀⠀⢀⠴⣁⣀⡠⣔⠬⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢄⠀⢳⡄⠈⠳⢤⡀⠀⠻⡦⣄⡀⠀⠀⠀⢸⠹⡌⢿⣷⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣾⣿⣿⣿⣿⣿⣇⠠⠀⢀⣾⣿⣿⣿⣿⡶⢤⣀⠈⠑⠳⠖⠠⠤⠤⠤⠤⠀⠒⠊⠉⠀⠀⠀⠀⠀⢀⣠⣮⡁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⠀⣙⣦⡀⠀⠈⠑⠄⡘⢌⠒⠍⣐⠒⢎⠀⠙⣆⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡘⠀⣼⣿⣿⣿⣿⡿⣷⡀⠈⠉⠒⠶⠤⢤⣀⣀⢀⣀⣀⣀⡀⡀⢀⣀⣠⠴⠂⠁⢹⣷⢳⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠴⡠⠤⢀⠠⠕⠚⢦⣀⠉⢊⠀⢀⠘⢧⣙⡿⢿⣿⣿⣿⣿⣟⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⢰⣿⣿⣿⣿⣿⣿⡿⢡⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠉⠉⠁⠁⠀⠈⢀⠀⠀⠘⠃⡆⢣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠀⠒⠂⠈⠁⠀⠀⢹⠀⠀⠊⢄⠛⣤⣀⠈⠛⠿⣷⣯⣟⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡃⠆⠀⠀⠀⢰⠁⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
#
# This is a Miku.
# ----------------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------------
# ClassSays 配置文件
#
# 几乎每个配置项都有详细的注释，请仔细阅读。
# 格式=> 键: 值 # YML 内格式, 补充格式 说明
# YML 内格式是 YML 语言的配置格式，如 Boolean(布尔值)、Number(数字)、String(字符串)、Array(数组)、Object(对象)、~(Null)。
# 补充格式是其应当遵守的其他格式，如 URL(统一资源定位器)、颜色(Hex 或 RGB)、JSON Object(JavaScript 对象)。
# [ a | b | c ] 代表可选值，a、b、c 分别代表可选值，N 选 1.
# ----------------------------------------------------------------------------------------------------------------------------

# -----------------------------------------
# 主渲染开关
# -----------------------------------------
enable: true # Boolean, 是否启用 ClassSays 主渲染，设置为 false 则不渲染任何内容

# -----------------------------------------
# 后端地址
# -----------------------------------------
api:
  enable: true # Boolean, 是否启用后端 API 功能，设置为 false 则不启用 API
  url: "http://localhost:3000" # String, URL 后端 API 地址，留空则使用默认地址




# -----------------------------------------
# 顶部菜单栏设置
# -----------------------------------------
nav:
  title: "ClassSays"
  menu:
    enable: true
    items:
      # 普通链接
      - label: "首页"
        url: "/"
        icon: "fas fa-home"
      
      # # 搜索按钮（特殊类型）
      # - label: "搜索"
      #   type: "search"
      #   icon: "fas fa-search"
      
      # 普通链接（无图标）
      - label: "关于"
        url: "/about"
        icon: "fa-solid fa-circle-info"
      - label: "切换夜间模式(临时)"
        url: "javascript:lightDarkTheme.toggleTheme();"
        icon: "fa-solid fa-moon"
      
      
      # 高级自定义链接（带额外属性）
      - label: "GitHub"
        type: "advanced"
        url: "https://github.com/admincmd-a/classSays"
        icon: "fas fa-external-link"
        target: "_blank"

      # 下拉菜单（有子项）
      # - label: "班级分类"
      #   icon: "fas fa-folder"
      #   children:
      #     - label: "名人名言"
      #       url: "/quotes"
      #       icon: "fas fa-quote-left"
      #     - label: "硬件维修实录"
      #       url: "/repair"
      #       icon: "fas fa-microchip"
      
      # 直接插入 HTML（完全自定义）
      # - type: "html"
      #   html: '<div class="custom-badge">🔥 中考倒计时</div>'

# -----------------------------------------
# 主题设置
# -----------------------------------------

themes:
  enable: true # 是否启用颜色主题功能
  mode: auto # 自动模式（跟随系统）/ 手动模式（跟随用户）
  auto_switch_dark_mode: true # 自动切换夜间模式（仅在自动模式下生效）
  default: "蔚蓝档案" # 默认主题
  items:
    - name: "蔚蓝档案" # 这是什么奇怪的主题名
      type: "light"
      colors:
        primary: "#0077be" # 主色调
        accent: "#ff6f00" # 强调色调
        secondary: "#00bfff" # 次要色调
        success: "#28a745" # 成功色
        info: "#17a2b8" # 信息色
        warning: "#ffc107" # 警告色
        error: "#dc3545" # 错误色
        light: "#f8f9fa" # 浅色
        dark: "#343a40" # 深色
        muted: "#6c757d" # 灰色
        white: "#fff" # 白色
        black: "#000" # 黑色
    - name: "蔚蓝档案"
      type: "dark"
      colors:
        primary: "#0077be"
        accent: "#ff6f00"
        secondary: "#00bfff"
        success: "#28a745"
        info: "#17a2b8"
        warning: "#ffc107"
        error: "#dc3545"
        light: "#f8f9fa"
        dark: "#343a40"
        muted: "#6c757d"
        white: "#fff"
        black: "#000"
    

# ----------------------------------------------------------------------------------------------------------------------------
# APlayer (音乐播放器)
# https://github.com/DIYgod/APlayer
# https://aplayer.js.org/#/home
# ----------------------------------------------------------------------------------------------------------------------------

aplayer:
  enable: true # Boolean, 是否启用音乐播放器，他是吸低的
  js: # String, 自定义 APlayer 的 js 文件路径，留空则使用默认路径
  css: # String, 自定义 APlayer 的 css 文件路径，留空则使用默认路径

  lrcType: # [ 1 | 2 | 3 ] 歌词取值类型 ,若空 为 3
  themeColor: # String, 主题颜色，留空则使用默认颜色
  audio: # Array, 音乐列表
    - name: "勾指起誓"
      artist: "洛天依 / ilem"
      url: "https://npm.elemecdn.com/musiccdn-ariasaka/music/%E5%8B%BE%E6%8C%87%E8%B5%B7%E8%AA%93.mp3"
      cover: "https://npm.elemecdn.com/musiccdn-ariasaka/pic/%E5%8B%BE%E6%8C%87%E8%B5%B7%E8%AA%93.jpg"
      lrc: "https://npm.elemecdn.com/musiccdn-ariasaka/lyric/%E5%8B%BE%E6%8C%87%E8%B5%B7%E8%AA%93.lrc"
      theme: ""
  
  config: # String, JSON Object APlayer 配置项，此项将覆写以上配置，务必指定container: document.getElementById('aplayer'),fixed: true,
  # 具体请参考 https://aplayer.js.org/#/home

welcomeMessage:
  enable: true # Boolean, 是否启用欢迎语
  api:
    use: # Boolean | String, 是否使用 API 获取欢迎语，留空则不使用 API
    url: # String, API 地址，留空则使用默认地址
  
  display:
    ip: # Boolean, 是否显示 IP 地址
    dist: # Boolean, 是否显示所在地区
    time: # Boolean, 是否显示当前时间
    timeChange: # Boolean, 是否显示适时语
    # weather: # Boolean, 是否显示天气信息

  posdesc:
    enable: # Boolean, 是否启用位置描述
    items: # String, JSON Array, 位置描述列表，留空则使用默认列表
      "{
          日本: `よろしく、一緒に桜を見に行きますか？`,
          美国: `Make America Great Again!`,
          英国: `I'd like to ride the London Eye with you at night.`,
          俄罗斯: `До дна эту водку!`,
          法国: `C'est La Vie`,
          德国: `Die Zeit verging im Fluge.`,
          澳大利亚: `Let's go to the Great Barrier Reef together!`,
          加拿大: `Prenez une feuille de carte et vous la donnez.`,
          南极洲: `南极洲的风很大，你一定记得要带伞！`,
          中国: {
              connectProvincesCities: true,
              北京市: {municipalities: true, content: `北——京——欢迎您~~~` },
              天津市: {municipalities: true, content: `讲段相声吧。` },
              重庆市: `高德地图:已到达重庆，下面切换百度地图导航。百度地图：已到达重庆，下面切换高德地图导航。`,
              河北省: `山势巍巍成壁垒，天下雄关。铁马金戈由此向，无限江山。`,
              山西省: `展开坐具长三尺，已占山河五百余。`,
              内蒙古自治区: `天苍苍，野茫茫，风吹草低见牛羊。`,
              辽宁省: `我想吃烤鸡架！`,
              吉林省: `状元阁就是东北烧烤之王。`,
              黑龙江省: `哈尔滨红肠,东北饺子`,
              上海市: {
                  municipalities: true,
                  content: `众所周知，中国只有 3 个城市。`
              },
              江苏省: {
                  南京市: `欢迎来自安徽省南京市的小伙伴`,
                  苏州市: `东方威尼斯`,
                  default: `散装的必须是散装的`
              },
              浙江省: `东风渐绿西湖柳，雁已还人未南归。`,
              安徽省: `蚌埠住了，芜湖起飞。`,
              福建省: `井邑白云间，岩城远带山。`,
              江西省: `落霞与孤鹜齐飞，秋水共长天一色。`,
              山东省: `遥望齐州九点烟，一泓海水杯中泻。`,
              湖北省: {
                  武汉市: {
                      authorLocations: true,
                      汉阳区: `知音故里`,
                      江夏区: `楚天首县`,
                      default: `九省通衢`
                  },
                  咸宁市: `桂花之乡`,
                  default: `荆楚门户`
              },
              河南省: `74751，长沙斯塔克。`,
              广东省: `老板来两斤福建人。`,
              广西壮族自治区: `桂林山水甲天下。`,
              海南省: `朝观日出逐白浪，夕看云起收霞光。`,
              四川省: `康康川妹子。`,
              贵州省: `茅台，学生，再塞200。`,
              云南省: `玉龙飞舞云缠绕，万仞冰川直耸天。`,
              西藏自治区: `躺在茫茫草原上，仰望蓝天。`,
              陕西省: `来份臊子面加馍。`,
              甘肃省: `羌笛何须怨杨柳，春风不度玉门关。`,
              青海省: `牛肉干和老酸奶都好好吃。`,
              宁夏回族自治区: `大漠孤烟直，长河落日圆。`,
              新疆维吾尔自治区: `驼铃古道丝绸路，胡马犹闻唐汉风。`,
              台湾省: `我在这头，大陆在那头。`,
              香港特别行政区: `永定贼有残留地鬼嚎，迎击光非岁玉。`,
              澳门特别行政区: `性感荷官，在线发牌。`,
              香港特别行政区: {specialAdministrativeRegion: true,content: `东方之珠`},
              default: `社会主义大法好!`
          },
          default: `带我去你的国家看看吧。`
      }"

    # 访客位置描述
    # 允许的参数 -> ${pos}, ${address}, ${timeChange}, ${dist}, ${posdesc}, ${ip}
    message: "欢迎来自 <span>${pos}</span> 的 ${address}，${timeChange}<br />你距我约有 <span>${dist}</span> 公里，${posdesc}，你的 IP 地址是 ${ip}<hr>"
    error_meesage: Welcome



# ----------------------------------------------------------------------------------------------------------------------------
# 白天模式和黑夜模式切换时的 JavaScript 脚本
# ----------------------------------------------------------------------------------------------------------------------------
# 它将在切换和初始化时执行
# 若你想在切换时执行一些操作，请在这里写下
# 若不起效果，请在网页控制台中运行 
# @code {errorCodes.getErrors(0x01010)} (LIGHT) 或 @code {errorCodes.getErrors(0x01011)} (DARK)
# 以查找发生的异常，通常控制台里也会有
# 注：FUNCTION 函数不得留空，否则会报错，如删除请填入 nullFunction
lightDarkMode:
  light: # 亮色主题
    js: ""
    function: nullFunction
  dark: # 暗色主题
    js: ""
    function: nullFunction

